// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaAPI.Data;

#nullable disable

namespace PizzaAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("PizzaAPI.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDeliveryTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDetails")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrderPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderStartingTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("1bb1c44f-87ef-46b6-8031-ca09cc419624"),
                            OrderDate = "2/10/22",
                            OrderDeliveryTime = "11:11 AM",
                            OrderDetails = "Deliver at front door",
                            OrderLocation = "SW 3, White Ave, Burnaby, BC V5G 3H2",
                            OrderPrice = 29.99m,
                            OrderStartingTime = "10:11 AM",
                            OrderStatus = "Complete"
                        },
                        new
                        {
                            OrderId = new Guid("24a36310-6c27-424d-8eaf-238fabe3298a"),
                            OrderDate = "2/10/22",
                            OrderDeliveryTime = "",
                            OrderDetails = "Deliver at back door",
                            OrderLocation = "7399 122 St, Surrey, BC V3W 5J2",
                            OrderPrice = 35.99m,
                            OrderStartingTime = "10:11 AM",
                            OrderStatus = "In Process"
                        },
                        new
                        {
                            OrderId = new Guid("d5473fbd-b5d2-427a-8561-0de46b84da4a"),
                            OrderDate = "2/10/22",
                            OrderDeliveryTime = "11:11 AM",
                            OrderDetails = "Deliver at side door",
                            OrderLocation = "2100 Viceroy Pl, Richmond, BC V6V 1Y9",
                            OrderPrice = 25.99m,
                            OrderStartingTime = "10:11 AM",
                            OrderStatus = "Complete"
                        });
                });

            modelBuilder.Entity("PizzaAPI.Models.Pizza", b =>
                {
                    b.Property<Guid>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PizzaDescription")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("PizzaType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PizzaId");

                    b.HasIndex("OrderId");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            PizzaId = new Guid("c12cda48-fa5c-4629-a844-ea8169d77187"),
                            OrderId = new Guid("d5473fbd-b5d2-427a-8561-0de46b84da4a"),
                            PizzaDescription = "Extra spicy",
                            PizzaType = 4
                        },
                        new
                        {
                            PizzaId = new Guid("ad7ca64a-acc4-42b1-b7e1-8372a29329ee"),
                            OrderId = new Guid("d5473fbd-b5d2-427a-8561-0de46b84da4a"),
                            PizzaDescription = "Normal Cheese Pizza",
                            PizzaType = 0
                        },
                        new
                        {
                            PizzaId = new Guid("9b1acd4c-d3cc-41c7-bbf8-2d318b2d32af"),
                            OrderId = new Guid("24a36310-6c27-424d-8eaf-238fabe3298a"),
                            PizzaDescription = "No Pinapples",
                            PizzaType = 1
                        },
                        new
                        {
                            PizzaId = new Guid("84a4c8d7-05ef-4501-b083-d04659e1b189"),
                            OrderId = new Guid("24a36310-6c27-424d-8eaf-238fabe3298a"),
                            PizzaDescription = "Extra BBQ Sause",
                            PizzaType = 3
                        },
                        new
                        {
                            PizzaId = new Guid("12e4ab6c-a818-43a9-9211-8b3bf5381448"),
                            OrderId = new Guid("24a36310-6c27-424d-8eaf-238fabe3298a"),
                            PizzaDescription = "No sauce",
                            PizzaType = 2
                        },
                        new
                        {
                            PizzaId = new Guid("b298ae88-5093-4e10-b559-dd9715ed03f7"),
                            OrderId = new Guid("1bb1c44f-87ef-46b6-8031-ca09cc419624"),
                            PizzaDescription = "Normal Cheese Pizza",
                            PizzaType = 0
                        },
                        new
                        {
                            PizzaId = new Guid("32f24690-cc94-4120-ade3-5e04e3c6f267"),
                            OrderId = new Guid("1bb1c44f-87ef-46b6-8031-ca09cc419624"),
                            PizzaDescription = "Extra Cheese and Extra Sause",
                            PizzaType = 0
                        });
                });

            modelBuilder.Entity("PizzaAPI.Models.Pizza", b =>
                {
                    b.HasOne("PizzaAPI.Models.Order", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaAPI.Models.Order", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
